-- =========================================================
-- DDL ORACLE – Hermes Reply (DER)
-- Compatível com Oracle 12c+ (IDENTITY)
-- =========================================================

-- Tabela: PECAS
CREATE TABLE PECAS (
    id_peca           NUMBER GENERATED BY DEFAULT AS IDENTITY
                      CONSTRAINT PK_PECAS PRIMARY KEY,
    tipo              VARCHAR2(100) NOT NULL,
    fabricante        VARCHAR2(100),
    tempo_uso_total   NUMBER
);

-- Tabela: SENSORES
CREATE TABLE SENSORES (
    id_sensor    NUMBER GENERATED BY DEFAULT AS IDENTITY
                 CONSTRAINT PK_SENSORES PRIMARY KEY,
    tipo_sensor  VARCHAR2(50) NOT NULL,
    id_peca      NUMBER
                 CONSTRAINT FK_SENSORES_PECAS
                 REFERENCES PECAS(id_peca)
                 ON DELETE SET NULL
);

-- Índice para a FK (boa prática)
CREATE INDEX IX_SENSORES_ID_PECA ON SENSORES(id_peca);

-- Tabela: CICLOS_OPERACAO
CREATE TABLE CICLOS_OPERACAO (
    id_ciclo     NUMBER GENERATED BY DEFAULT AS IDENTITY
                 CONSTRAINT PK_CICLOS_OPERACAO PRIMARY KEY,
    id_peca      NUMBER
                 CONSTRAINT FK_CICLOS_PECAS
                 REFERENCES PECAS(id_peca)
                 ON DELETE CASCADE,
    data_inicio  TIMESTAMP,
    data_fim     TIMESTAMP,
    duracao      NUMBER  -- unidade a seu critério (min/seg/h)
);

CREATE INDEX IX_CICLOS_ID_PECA ON CICLOS_OPERACAO(id_peca);

-- Tabela: LEITURAS_SENSOR
CREATE TABLE LEITURAS_SENSOR (
    id_leitura          NUMBER GENERATED BY DEFAULT AS IDENTITY
                        CONSTRAINT PK_LEITURAS_SENSOR PRIMARY KEY,
    id_sensor           NUMBER
                        CONSTRAINT FK_LEITURAS_SENSORES
                        REFERENCES SENSORES(id_sensor)
                        ON DELETE CASCADE,
    leitura_valor       NUMBER(12,4), -- ajuste precisão conforme necessidade
    leitura_data_hora   TIMESTAMP
);

CREATE INDEX IX_LEITURAS_ID_SENSOR ON LEITURAS_SENSOR(id_sensor);

-- Tabela: FALHAS
CREATE TABLE FALHAS (
    id_falha    NUMBER GENERATED BY DEFAULT AS IDENTITY
                CONSTRAINT PK_FALHAS PRIMARY KEY,
    id_peca     NUMBER
                CONSTRAINT FK_FALHAS_PECAS
                REFERENCES PECAS(id_peca)
                ON DELETE CASCADE,
    descricao   VARCHAR2(255),
    data        TIMESTAMP
);

CREATE INDEX IX_FALHAS_ID_PECA ON FALHAS(id_peca);

-- Tabela: ALERTAS
CREATE TABLE ALERTAS (
    id_alerta    NUMBER GENERATED BY DEFAULT AS IDENTITY
                 CONSTRAINT PK_ALERTAS PRIMARY KEY,
    id_falha     NUMBER
                 CONSTRAINT FK_ALERTAS_FALHAS
                 REFERENCES FALHAS(id_falha)
                 ON DELETE CASCADE,
    nivel_risco  VARCHAR2(20)
);

CREATE INDEX IX_ALERTAS_ID_FALHA ON ALERTAS(id_falha);
